//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WU_Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTest
    {
        public long StudentId { get; set; }
        public long ClassId { get; set; }
        public Nullable<decimal> FirstScore { get; set; }
        public Nullable<decimal> SecondScore { get; set; }
        public Nullable<decimal> ThirdScore { get; set; }
    
        public virtual CertificateClass CertificateClass { get; set; }
        public virtual Student Student { get; set; }
    }
}
